# Logging

# Bluetooth

# Wi-Fi

# 802.15.4 (for UWB transceiver drivers)



CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_LOG=y
CONFIG_GPIO=y
# CONFIG_I2C=y



# Enable C++ Support
CONFIG_CPP=y
CONFIG_STD_CPP17=y
# CONFIG_LIB_CPLUSPLUS=y

# Enable C++ Runtime Features
CONFIG_CPP_EXCEPTIONS=n
CONFIG_CPP_RTTI=n
CONFIG_I2C=y

CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_LOG_BACKEND_SHOW_COLOR=n



# Use full C++ standard library /for srl  containers


# Use Newlib as the C library (required for full C++ features)
CONFIG_NEWLIB_LIBC=y
CONFIG_REQUIRES_FULL_LIBCPP=y
# CONFIG_MCUBOOT_UPDATE_FOOTER_SIZE=0x30




#mcu  mgr for OTA 
# CONFIG_MCUMGR=y

CONFIG_BOOTLOADER_MCUBOOT=y


#modem subsys
CONFIG_MODEM_MODULES=y
CONFIG_MODEM_PIPE=y

#enabling the backend dastsctures  for the data to be collected
CONFIG_MODEM_BACKEND_UART=y
# CONFIG_UART_INTERRUPT_DRIVEN=y

# Helper Modules
CONFIG_MODEM_CHAT=y
CONFIG_MODEM_DEDICATED_WORKQUEUE=y
CONFIG_MODEM_DEDICATED_WORKQUEUE_STACK_SIZE=2048
